pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/mansuree-suhail/tutedude_jenkins.git'
            }
        }
        stage('Install dependencies') {
            steps {
                dir('frontend') {  // change to your frontend folder
                    sh 'npm install'
                }
            }
        }
        stage('Deploy') {
            steps {
                dir('frontend') {  // run deployment from frontend folder
                    sh 'pm2 restart express-app || pm2 start "node app.js" --name express-app'
                }
            }
        }
    }
}

