pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/mansuree-suhail/tutedude_jenkins.git'
            }
        }
        stage('Install dependencies') {
            steps {
                sh 'python3 -m pip install --upgrade pip'
                sh 'pip3 install -r requirements.txt'
            }
        }
        stage('Deploy') {
            steps {
                sh 'pm2 restart flask-app || pm2 start "python3 app.py" --name flask-app'
            }
        }
    }
}

