pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/mansuree-suhail/tutedude_jenkins.git'
            }
        }
        stage('Install dependencies') {
            steps {
                sh '''
                python3 -m venv venv               # create virtual environment
                . venv/bin/activate           # activate it
                pip install --upgrade pip
                pip install -r backend/requirements.txt
                '''
            }
        }
        stage('Deploy') {
            steps {
                sh '''
                . venv/bin/activate           # activate virtual env before running app
                pm2 restart flask-app || pm2 start "python3 app.py" --name flask-app
                '''
            }
        }
    }
}

